version: "3"

services:
  misskey-ebooks-bot:
    build:
      context: ./
    container_name: misskey-ebooks-bot
    user: 1000:1000
    restart: always
    volumes:
      - ./bot.cfg:/usr/src/app/bot.cfg
